### ISSUE TITLE
Time to Update to 1.0!

### ISSUE THREAD

**Issue by nickeubank** [JuliaDocs/Julia-Cheat-Sheet#19]
I'm not fully up to date on what all has changed in 1.0, but wanted to start a list of things to update. 

- [ ] Add section on `missing` types (and remove from Data Frames)
- [ ] Update `Package Management` section for Pkg3
- [ ] Add named tuples 
- [ ] Noteworthy packages and projects needs a big update. I would add more of the "families": `JuliaGraphs`, `JuliaOpt`, etc.
- [ ] Performance tips are mostly out of date I think
- [ ] Add JuliaCon 2018 to videos, as well as videos on `julialang`
- [ ] Maybe update the aesthetic to be a little more modern than current purple-to-blue color fade in headers?
- [ ] Add section on REPL tricks?

I'm sure there are more that insiders will know...

A

**Comment by kirtsar** [comment]
**REPL**
? - enter "help mode"
] - enter "package mode"
; - enter "command-line mode"
additional modes can be provided in different packages
no more workspace(). Use Revise.jl or something like that.

**Numbers**
I think it should be splitted into actual numbers and random numbers, because for random numbers one might want to use seed, for example; MersenneTwister is not more in Base, but in Random, so use should use `import Random`.
No more iround(), maybe you should use round(Int, n) instead. 
More words about round; for example, rounding up to some digits.

**Mathematics**
No more e, catalan, golden_ratio in Base. Use `using Base.MathConstants` or Combinatorics package instead (for example). You can use exp(1) for exponent. 
Many of matrix calculations were moved from Base to LinearAlgebra, so firstly you should use `using LinearAlgebra`. 
Use tr for trace.
Scalar products of two vectors, matrix decomposition and so on are also live here.
Matrix identity is `I`. Actually, this is a special type UniformScaling for better performance.

**Control flow and loops**
Something about eachindex, CartesianIndexing and LinearIndexing can be added.

**Functions**
`function foo{T<:Number}(num::T)::String` is not allowed anymore. You should write this as:
`function foo(num::T)::String where T <: Number`
Maybe something else can be said here. I do not know anything about Trampolining.

**Arrays**
I think
Access and assignment: `arr[1] = "Some text"` is ambiguos, because:
1. It is written `arr = Float64[]` just two lines above this line.
2. Even if you write arr[1] = 1.0, it is still unacceptable, there will be an error that you try to access 0-elements array. Arrays should be initialized before use.
No linspace function. You can use LinRange(start, stop, size) instead (or collect(a : b : c), but i suppose there can be some issues).

**Types**
Abstract type declaration has changed:
`abstact type A end`
`supertype(a)` instead of `super(a)`.
No more nullable type. I suppose you should use Union{Missing, T} instead.
Some examples must be provided with inner and outer type constructions and with recursive types, such as tree nodes with leaves.

**DataFrames**
Change pool! function from DataFrames to categorical!(df, :A)
We should check these things about missings.

**Packages**
Should be reconsidered. No flux, no knet, no mxnet, no lightgraphs, no juliaml

**Performance tips**
_Devectorize code with for loops unlike R, MATLAB or Python_ definitely not true anymore. Vectorized operations are OK (if you do it properly). Add description of syntactic loop fusion: https://julialang.org/blog/2017/01/moredots.

We need more fresh references.

**Comment by nickeubank** [comment]
Terrific! Thanks @kirtsar ! I started a PR to try and integrate the issues I saw (#20). If you want to make any changes to that please feel free to, or I"ll try and integrate more of that when I have a chance (though may take a couple weeks).

**Comment by michi-zuri** [comment]
it should be exit() not quit() to leave the REPL
