### ISSUE TITLE
How to manage updates across translations?

### ISSUE THREAD

**Issue by nickeubank** [JuliaDocs/Julia-Cheat-Sheet#97]
Now that we've had so many people do AMAZING work translating this, it occurs to me we have a new problem: how do we manage changes to the cheat-sheet? Most of us do NOT know Spanish, Portuguese, and Mandarin, so aren't suited to making changes in all translations. But we also want to allow people to update content. 

Suggestions?

**Comment by nickeubank** [comment]
I don't think that quite fixes it. 

Suppose we decide to, say, add a new panel on DataFrames.jl. I can do that in english (and could maybe pull off in Spanish). But how to we make sure that all the translations stay in sync?

**Comment by brakmic** [comment]
Well, this is a hard question to answer.

**Comment by waldyrious** [comment]
I think we'd need to use some translation platform to manage translations. That does introduce some overhead, but it would also make the translation process more streamlined (people could translate individual sentences rather than entire files, we would have graphical progress indicators per language, etc.), and of course, there would be an indication of exactly which bits become outdated when the source language changes.

Weblate for example is one such platform that IIRC integrates well with GitHub.
